version: '3'
services:
  app:
    build: .
    container_name: 'ml_school'
    tty: true
    volumes:
      # マウントするディレクトリ
      - .:/app
    ports:
      # ホスト側のポート：コンテナ側のポート
            - 8002:8002
