services:
  app:
    build: .
    container_name: 'MNIST-classification-web-app'
    tty: true
    volumes:
      # マウントするディレクトリ
      - .:/app
    ports:
      # ホスト側のポート：コンテナ側のポート
            - 8000:8000
